name: CI
on:
  pull_request:
    branches: [develop, master]  
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      
      - name: Build Project
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: npm run build
      - name: Display structure of build files
        run: ls -R
        working-directory: build
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
      - name: Upload Build Folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Downlaod Build Folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build    
      - name: Deploy to Staging
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: echo "Deploying.."